name: Change Octocat style

on:
  issues:
    types: [opened, edited]

jobs:
  detect_style_type:
    name: Detect style type
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'Octocat style')

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get Style type
      uses: actions/github-script@v3
      id: getStyleType
      with:  
        result-encoding: json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          console.log(context.payload.issue.body)
          let rgx = /\-\s\[x\]\s(.*)/gm
          let rgxMatch = rgx.exec(context.payload.issue.body)
          
          console.log(rgxMatch)
          if (rgxMatch) {
            let checkValue = rgxMatch[1]
            console.log(checkValue)
            let newBody = context.payload.issue.body

            if (checkValue.includes('<!--checked style-->')) {
              // Style was already selected 
              checkValue = checkValue.replace('<!--checked style-->', '')
            } else {
              // Style was not already selected. We need to provide options.
              newBody = newBody.replace(checkValue, `${checkValue}<!--checked style-->`)

              const fs = require('fs')
              fs.readFile(`./.github/styles/${checkValue}.md`, 'utf8' , (err, data) => {
                if (err) {
                  console.error(err)
                  return
                } else {
                  newBody = newBody + '\n<!--style options-->' + data
                  github.issues.update(
                    {
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      issue_number: context.payload.issue.number,
                      body: newBody
                    }
                  )
                }
              })
            } 
          }