# This is a basic workflow that is manually triggered

name: Create repo

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Name of the Octocat'
        # Default value if no value is explicitly provided
        default: 'Summertocat'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
    - name: Create repo
      run: |
        gh --version
        echo ${{ secrets.TOKEN }} | gh auth login --with-token
        gh repo create --confirm --public --description 'A custom Octocat' --template summerfest-2021/myoctocat summerfest-2021/${{github.event.inputs.name}}
