# This is a basic workflow that is manually triggered

name: Create repo

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Name of the Octocat'
        # Default value if no value is explicitly provided
        default: 'Summertocat'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
    - name: Create repo
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.TOKEN }}
        script: |
          github.repos.createUsingTemplate(
            {
              owner: context.repo.owner,
              name: '${{github.event.inputs.name}}',
              template_repo: context.repo.name,
              template_owner: context.repo.owner
            }
          )
          
          
